using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Mono.Cecil;
using Mono.Cecil.Cil;

namespace Papier
{
    /// <summary>
    /// This class is responsible for generating syntax tree/string stub classes from CECIL Assembly Metadata.<br />
    /// This is required because we compile individual classes, which have references to other classes of the given
    /// assembly. It is not possible, however, to add the assembly as a reference to the compiler, because that
    /// introduces class duplicates, that cannot be cast into each other (different assemblies).<br />
    /// As a workaround, we compile the changed classes together with a lot of stub classes (stub because that is more
    /// reliable than using a decompiler and have full blown methods, in fact the method bodies are irrelevant anyway).
    /// </summary>
    public class StubGenerator
    {
        // 4 spaces ident, hard coded :D
        private const string Ident = "    ";
        public static async Task CreateStringStub(Stream stringStream, TypeDefinition stubType, HashSet<IMemberDefinition> stubDefinitions)
        {
            await using (var sw = new StreamWriter(stringStream))
            {
                // We use FQN, so we don't need to care about usings

                await sw.WriteLineAsync("// This file has been AUTOGENERATED by Papier. Changes may be LOST.");
                await sw.WriteLineAsync("// If compilation fails because of invalid stubs, open a ticket.");
                await sw.WriteLineAsync(
                    "// As a short-term resolution, you can also fix this file and instruct Papier to _not_ overwrite existing stubs!");
                await sw.WriteLineAsync(
                    "// Note that in the most cases entire stub classes may be missing and won't be picked up by the compiler");

                if (!string.IsNullOrEmpty(stubType.Namespace))
                {
                    await sw.WriteLineAsync($"namespace {stubType.Namespace} {{");
                }

                var modifier = GetModifiers(stubType);

                // Methods that need to be implemented from an interface or that are abstract on a baseclass.
                var requiredMethods = new List<MethodDefinition>();
                var subClasses = "";

                if (stubType.BaseType != null || stubType.HasInterfaces)
                {
                    subClasses = ": ";
                }

                if (stubType.BaseType != null)
                {
                    subClasses += NamespacedType(stubType.BaseType);
                    // TODO: Go down type hierarchy and take abstract methods.
                }

                if (stubType.HasInterfaces)
                {
                    foreach (var iface in stubType.Interfaces)
                    {
                        var itype = iface.InterfaceType;
                        subClasses += $", {NamespacedType(itype)}";
                        
                        // TODO: Ignore default method impls and validate that.
                        requiredMethods.AddRange(itype.Resolve().Methods.Where(m => !m.IsStatic && !m.HasBody));
                    }
                }

                await sw.WriteLineAsync("[PapierStub]");
                await sw.WriteLineAsync($"{modifier}class {stubType.Name}{subClasses} {{");

                await sw.WriteLineAsync($"{Ident}#region Fields");
                foreach (var fd in stubDefinitions.Where(x => x is FieldDefinition).Cast<FieldDefinition>())
                {
                    await WriteField(sw, fd);
                }
                await sw.WriteLineAsync($"{Ident}#endregion");
                await sw.WriteLineAsync();
                
                await sw.WriteLineAsync($"{Ident}#region Props");
                foreach (var pd in stubDefinitions.Where(x => x is PropertyDefinition).Cast<PropertyDefinition>())
                {
                    await WriteProp(sw, pd);
                }
                await sw.WriteLineAsync($"{Ident}#endregion");
                await sw.WriteLineAsync();
                
                await sw.WriteLineAsync($"{Ident}#region Methods");
                foreach (var md in stubDefinitions.Where(x => x is MethodDefinition).Cast<MethodDefinition>())
                {
                    await WriteMethod(sw, md);
                }
                await sw.WriteLineAsync($"{Ident}#endregion");
                await sw.WriteLineAsync();
                
                await sw.WriteLineAsync($"{Ident}#region Overriden Methods");
                foreach (var md in requiredMethods)
                {
                    await WriteMethod(sw, md);
                }
                await sw.WriteLineAsync($"{Ident}#endregion");
                await sw.WriteLineAsync();
                
                await sw.WriteLineAsync($"}} // class {stubType.Name}");

                if (!string.IsNullOrEmpty(stubType.Namespace))
                {
                    await sw.WriteLineAsync($"}} // namespace {stubType.Namespace}");
                }
            } 
        }

        private static string NamespacedType(TypeReference type)
        {
            if (type.Namespace == "System" && type.Name == "Void")
            {
                return "void";
            }
            
            var mangledName = type.FullName;
            mangledName = Regex.Replace(mangledName, "`\\d+", "")
                .Replace("&", "");

            return mangledName;
        }

        private static async Task WriteField(TextWriter sw, FieldDefinition fd)
        {
            await sw.WriteLineAsync($"{Ident}{GetModifiers(fd)}{NamespacedType(fd.FieldType)} {fd.Name};");
        }
        
        private static async Task WriteProp(TextWriter sw, PropertyDefinition pd)
        {
            // Visibility is non-trivial here: If
            // 1) read- or write-only property -> The property defines the prefix-visibility attribute
            // 2) both properties have the same visibility -> They define the prefix-visibility attribute
            // 3) different visibilities -> The less restrictive is the prefix, the more restrictive in-place.

            var both = pd.GetMethod != null && pd.SetMethod != null;
            var prefix = "";
            var infix_get = false;
            var infix_set = false;

            if (!both)
            {
                prefix = GetModifiers(pd.GetMethod ?? pd.SetMethod);
            }
            else
            {
                var mod1 = GetModifiers(pd.GetMethod);
                var mod2 = GetModifiers(pd.SetMethod);

                if (mod1.Equals(mod2))
                {
                    prefix = mod1;
                }
                else
                {
                    if (pd.GetMethod.IsPublic)
                    {
                        prefix = mod1;
                        infix_set = true;
                    }
                    else
                    {
                        prefix = mod2;
                        infix_get = true;
                    }
                }
            }
            
            await sw.WriteLineAsync($"{Ident}{prefix}{NamespacedType(pd.PropertyType)} " +
                                    $"{pd.Name} {{ {(infix_get ? GetModifiers(pd.GetMethod) : "")}get; " +
                                    $"{(infix_set ? GetModifiers(pd.SetMethod) : "")}set;}}");
        }
        
        private static async Task WriteMethod(TextWriter sw, MethodDefinition md)
        {
            var parms = "";
            if (md.HasParameters)
            {
                foreach (var pd in md.Parameters)
                {
                    var defaultValue = "";
                    if (pd.IsOptional && pd.HasDefault && pd.HasConstant)
                    {
                        var constant = GetCodeRepresentation(pd.Constant);
                        if (pd.ParameterType.Resolve().IsEnum)
                        {
                            // For enums we need to cast
                            constant = $"({pd.ParameterType.FullName}) {constant}";
                        }
                        defaultValue = $" = {constant}";
                    }
                    parms += $"{GetModifiers(pd)}{NamespacedType(pd.ParameterType)} {pd.Name}{defaultValue}, ";
                }

                // This condition is in theory redundant...
                if (!string.IsNullOrEmpty(parms))
                {
                    parms = parms[..^2]; // remove trailing ", "
                }
            }

            if (md.IsConstructor)
            {
                // Constructors, as opposed to any other method, may _need_ to call the specific base-class constructor.
                // This is really not the domain of the stub generator....
                var @base = "";
                var bt = md.DeclaringType.BaseType?.Resolve();
                if (bt != null)
                {
                    // Idea: find the first call instruction that is a constructor of the basetype (well there can only be one)
                    // Not sure if we could stop after the first call in general, but who cares.
                    var constructor = md.Body.Instructions.Where(i =>
                            i.OpCode == OpCodes.Call || i.OpCode == OpCodes.Callvirt || i.OpCode == OpCodes.Calli)
                        .Select(i => i.Operand).Cast<MethodDefinition>()
                        .FirstOrDefault(cmd => cmd.IsConstructor && cmd.DeclaringType.Equals(bt));

                    if (constructor != null)
                    {
                        // Problem now: find a valid combination of md parameter-names, that correspond to constructor's
                        // parameter types. This can't be done perfectly (e.g. when a type occurs multiple times, or 
                        // when constructor requires a type not present in param), but it's only about stubbing here
                        // anyway. An alternative solution would inspect the opcode around the method call to find the
                        // arguments, but at that point we're writing a half decompiler.
                        @base = ": base(";

                        if (constructor.HasParameters)
                        {
                            var superParamList = md.Parameters.ToHashSet();
                            foreach (var cp in constructor.Parameters)
                            {
                                var cpt = cp.ParameterType.Resolve();
                                var sp = superParamList.FirstOrDefault(p => 
                                    IsAssignableFrom(cpt, p.ParameterType.Resolve()));

                                if (sp == null)
                                {
                                    await Console.Error.WriteLineAsync($"Could not find a matching parameter in {md} to pass to {constructor} for {cp}, passing null");
                                    @base += "null, ";
                                }
                                else
                                {
                                    superParamList.Remove(sp);
                                    @base += $"{sp.Name}, ";
                                }
                            }
                        }

                        @base = @base[..^2]; // remove trailing ", "
                        @base += ")";
                    }
                }
                
                await sw.WriteLineAsync(
                    $"{Ident}{GetModifiers(md)}{md.DeclaringType.Name}({parms}){@base} {{ }}");
            }
            else
            {
                var outParams = md.Parameters.Where(x => x.IsOut).ToList();
                var outAssignments = new StringBuilder();
                
                foreach (var param in outParams)
                {
                    var paramType = param.ParameterType;
                    if (param.ParameterType is ByReferenceType)
                    {
                        // TODO: We could use this resolution for types everywhere
                        paramType = paramType.GetElementType();
                    }
                    
                    outAssignments.Append($"{param.Name} = {GetDefaultReturnValueForType(paramType)}; ");
                }
                
                var returnStatement = GetReturnStatement(md.ReturnType);
                await sw.WriteLineAsync(
                    $"{Ident}{GetModifiers(md)}{NamespacedType(md.ReturnType)} {md.Name}({parms}) {{ {outAssignments}{returnStatement}}}");
            }
        }

        private static string GetReturnStatement(TypeReference type)
        {
            var def = GetDefaultReturnValueForType(type);

            if (def == null)
            {
                return "";
            }
            else
            {
                return $"return {def}; "; // Trailing whitespace intentional
            }
        }

        private static string? GetDefaultReturnValueForType(TypeReference type)
        {
            if (!type.Namespace.Equals("System"))
            {
                if (type.IsValueType)
                {
                    // TODO: In theory, we could check for the constructors and invoke it, but we wait until someone complains
                    return $"new {type.FullName}(); /* Value Type: best guess */";
                }
                else
                {
                    return "null";
                }
            }
            else
            {
                return type.Name switch
                {
                    "Void" => null,
                    "Boolean" => "false",
                    "Int32" => "0",
                    "UInt32" => "0",
                    "String" => "\"\"",
                    _ => "null"
                };
            }
        }

        private static string GetCodeRepresentation(object obj)
        {
            if (obj is bool b)
            {
                return b ? "true" : "false";
            }
            else if (obj is float f)
            {
                return $"{f}f";
            } else if (obj is double d)
            {
                return $"{d}d";
            }
            else
            {
                return obj.ToString();
            }
        }

        // TODO: More modifiers?
        private static string GetModifiers(FieldDefinition fd)
        {
            var modifiers = "";
            if (fd.IsPublic)
            {
                modifiers += "public ";
            }

            if (fd.IsPrivate)
            {
                modifiers += "private ";
            }

            if (fd.IsStatic)
            {
                modifiers += "static ";
            }

            return modifiers;
        }
        
        private static string GetModifiers(MethodDefinition md)
        {
            var modifiers = new StringBuilder();
            
            if (md.IsPublic)
            {
                modifiers.Append("public ");
            }

            if (md.IsPrivate)
            {
                modifiers.Append("private ");
            }

            if (md.IsStatic)
            {
                modifiers.Append("static ");
            }

            if (md.IsVirtual)
            {
                modifiers.Append("virtual ");
            }

            if (md.HasOverrides)
            {
                modifiers.Append("override ");
            }
            
            return modifiers.ToString();
        }
        
        private static string GetModifiers(TypeDefinition md)
        {
            var modifiers = "";
            if (md.IsPublic)
            {
                modifiers += "public ";
            }

            if (md.IsSealed)
            {
                modifiers += "sealed ";
            }
            
            return modifiers;
        }

        private static string GetModifiers(ParameterDefinition pd)
        {
            var modifiers = new StringBuilder();
            if (pd.IsIn)
            {
                modifiers.Append("in ");
            } else if (pd.IsOut)
            {
                modifiers.Append("out ");
            } else if (pd.ParameterType.IsByReference)
            {
                modifiers.Append("ref ");
            }
            
            return modifiers.ToString();
        }

        /// <summary>
        /// Determines if packedType can be assigned to a baseType, which means that baseType is an interface 
        /// implemented by packedType or a class that is extended.
        /// </summary>
        /// <param name="packedType"></param>
        /// <param name="baseType"></param>
        /// <returns></returns>
        public static bool IsAssignableFrom(TypeDefinition baseType, TypeDefinition packedType)
        {
            var curr = packedType;
            while (curr != null)
            {
                if (curr.Equals(baseType))
                {
                    return true;
                }

                if (baseType.IsInterface && curr.HasInterfaces)
                {
                    if (curr.Interfaces.Any(x => baseType.Equals(x.InterfaceType?.Resolve())))
                    {
                        return true;
                    }
                }
                
                curr = curr.BaseType?.Resolve();
            }

            return false;
        }
        
        public static void WriteStubAttribute(TextWriter sw) {
            sw.WriteLine("// This Attribute is auto-generated by Papier");
            sw.WriteLine("// Every stub method is annotated with it, so that when merging the IL, those stub classes get dropped");
            sw.WriteLine("[System.AttributeUsage(System.AttributeTargets.Class)]");
            sw.WriteLine("public class PapierStubAttribute : System.Attribute {");
            sw.WriteLine("    public PapierStubAttribute() {}");
            sw.WriteLine("}");
        }
    }
}